# permissions for end users to edit logstashes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logstash-editor-role
rules:
- apiGroups:
  - apps.russellgao.cn
  resources:
  - logstashes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.russellgao.cn
  resources:
  - logstashes/status
  verbs:
  - get
